// <auto-generated />
using GymApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymApp.Data.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20220424101758_First Migration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("GymApp.Data.Lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastName = "Lista 1",
                            Name = "Lista 1"
                        },
                        new
                        {
                            Id = 2,
                            LastName = "Lista 2",
                            Name = "Lista 2"
                        },
                        new
                        {
                            Id = 3,
                            LastName = "Lista 3",
                            Name = "Lista 3"
                        },
                        new
                        {
                            Id = 4,
                            LastName = "Lista 4",
                            Name = "Lista 4"
                        },
                        new
                        {
                            Id = 5,
                            LastName = "Lista 5",
                            Name = "Lista 5"
                        },
                        new
                        {
                            Id = 6,
                            LastName = "Lista 6",
                            Name = "Lista 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
