// <auto-generated />
using GymApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymApp.Data.Migrations
{
    [DbContext(typeof(GymDbContext))]
    partial class GymDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("GymApp.Data.Lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastName = "Cliente Apellido 1",
                            Name = "Cliente Nombre 1"
                        },
                        new
                        {
                            Id = 2,
                            LastName = "Cliente Apellido 2",
                            Name = "Cliente Nombre 2"
                        },
                        new
                        {
                            Id = 3,
                            LastName = "Cliente Apellido 3",
                            Name = "Cliente Nombre 3"
                        },
                        new
                        {
                            Id = 4,
                            LastName = "Cliente Apellido 4",
                            Name = "Cliente Nombre 4"
                        },
                        new
                        {
                            Id = 5,
                            LastName = "Cliente Apellido 5",
                            Name = "Cliente Nombre 5"
                        },
                        new
                        {
                            Id = 6,
                            LastName = "Cliente Apellido 6",
                            Name = "Cliente Nombre 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
